---
abstract: ~
author:
  - 'Toby Corkindale, C<< <tjc at wintrmute.net> >>'
  - 'Toby Corkindale <tjc@wintrmute.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-Store-Couchbase
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::ClassData: 0
  Catalyst::Plugin::Session: 0.27
  Couchbase::Client: 1
  Moose: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.94
